In [1]:
import pandas as pd
import numpy as np
import pickle

In [4]:
filename = '/Users/divya/AIML/Cr-03-PythonAndPandasForDataAnalysisAndDataManipulation/Materials/P87-Section-2-Dataset-Basics-Resources/P87-S2-Dataset-Basics-Resources\heart.csv'

In [6]:
df = pd.read_csv(filename)
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [8]:
data = np.loadtxt(filename, delimiter=",", skiprows=1)
print(data)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [9]:
data =np.genfromtxt(filename, delimiter=',', dtype=None, names=True, encoding="utf-8-sig")

In [11]:
print(data)
print(data.dtype)

[(63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1)
 (37, 1, 2, 130, 250, 0, 1, 187, 0, 3.5, 0, 0, 2, 1)
 (41, 0, 1, 130, 204, 0, 0, 172, 0, 1.4, 2, 0, 2, 1)
 (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1)
 (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1)
 (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1)
 (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1)
 (44, 1, 1, 120, 263, 0, 1, 173, 0, 0. , 2, 0, 3, 1)
 (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1)
 (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1)
 (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1)
 (48, 0, 2, 130, 275, 0, 1, 139, 0, 0.2, 2, 0, 2, 1)
 (49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2, 1)
 (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1)
 (58, 0, 3, 150, 283, 1, 0, 162, 0, 1. , 2, 0, 2, 1)
 (50, 0, 2, 120, 219, 0, 1, 158, 0, 1.6, 1, 0, 2, 1)
 (58, 0, 2, 120, 340, 0, 1, 172, 0, 0. , 2, 0, 2, 1)
 (66, 0, 3, 150, 226, 0, 1, 114, 0, 2.6, 0, 0, 2, 1)
 (43, 1, 0, 150, 247, 0, 1, 171, 0, 1.5, 2, 0,

In [14]:
#loading manually

def load_file(filename):
    with open(filename, encoding="utf-8-sig") as f:
        data, cols = [], []
        for i, line in enumerate(f.read().splitlines()):
            if i == 0:
                cols += line.split(",")
            else:
                data.append([float(x) for x in line.split(",")])

        df = pd.DataFrame(data, columns=cols)
    return df

load_file(filename).head()


age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0    0.0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0    0.0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0    0.0      1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0    0.0      0.8   
4  57.0  0.0  0.0     120.0  354.0  0.0      1.0    163.0    1.0      0.6   

   slope   ca  thal  target  
0    0.0  0.0   1.0     1.0  
1    0.0  0.0   2.0     1.0  
2    2.0  0.0   2.0     1.0  
3    2.0  0.0   2.0     1.0  
4    2.0  0.0   2.0     1.0

In [13]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [17]:
#dataframe to numpy array
data = df.values
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [18]:
data = df.to_numpy()
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [19]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [20]:
print(data.dtype, data)

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [21]:
data[0,0]=100

In [22]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [28]:
data

array([[100.,   1.,   3., ...,   0.,   1.,   1.],
       [ 37.,   1.,   2., ...,   0.,   2.,   1.],
       [ 41.,   0.,   1., ...,   0.,   2.,   1.],
       ...,
       [ 68.,   1.,   0., ...,   2.,   3.,   0.],
       [ 57.,   1.,   0., ...,   1.,   3.,   0.],
       [ 57.,   0.,   1., ...,   1.,   2.,   0.]])

In [29]:
df2 = df[["age","sex","cp"]]
data2 = df2.to_numpy()#.copy()
data2[0,0] = 100
df2.head()

age  sex  cp
0  100    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

In [27]:
df2 = df[["age","sex","cp"]]
data2 = df2.to_numpy().copy()
data2[0,0] = 100
df2.head()

age  sex  cp
0   63    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

In [30]:
print(df["age"].mean(), df["age"].to_numpy().mean())

54.366336633663366 54.366336633663366


In [31]:
print(df['age'].quantile(0.5))

55.0


In [34]:
#print(df['age'].reshape((3,-1)))
df['age'].to_numpy().reshape((3,-1))

array([[63, 37, 41, 56, 57, 57, 56, 44, 52, 57, 54, 48, 49, 64, 58, 50,
        58, 66, 43, 69, 59, 44, 42, 61, 40, 71, 59, 51, 65, 53, 41, 65,
        44, 54, 51, 46, 54, 54, 65, 65, 51, 48, 45, 53, 39, 52, 44, 47,
        53, 53, 51, 66, 62, 44, 63, 52, 48, 45, 34, 57, 71, 54, 52, 41,
        58, 35, 51, 45, 44, 62, 54, 51, 29, 51, 43, 55, 51, 59, 52, 58,
        41, 45, 60, 52, 42, 67, 68, 46, 54, 58, 48, 57, 52, 54, 45, 53,
        62, 52, 43, 53, 42],
       [59, 63, 42, 50, 68, 69, 45, 50, 50, 64, 57, 64, 43, 55, 37, 41,
        56, 46, 46, 64, 59, 41, 54, 39, 34, 47, 67, 52, 74, 54, 49, 42,
        41, 41, 49, 60, 62, 57, 64, 51, 43, 42, 67, 76, 70, 44, 60, 44,
        42, 66, 71, 64, 66, 39, 58, 47, 35, 58, 56, 56, 55, 41, 38, 38,
        67, 67, 62, 63, 53, 56, 48, 58, 58, 60, 40, 60, 64, 43, 57, 55,
        65, 61, 58, 50, 44, 60, 54, 50, 41, 51, 58, 54, 60, 60, 59, 46,
        67, 62, 65, 44, 60],
       [58, 68, 62, 52, 59, 60, 49, 59, 57, 61, 39, 61, 56, 43, 62, 63,
      

In [35]:
#creating dtaframe
import numpy as np
import pandas as pd

In [37]:
data = np.random.random(size=(5,3))
print(data)

[[0.47509319 0.20479899 0.6616246 ]
 [0.51652796 0.46397519 0.94409136]
 [0.45380937 0.15076179 0.67561458]
 [0.82501621 0.47982071 0.68263859]
 [0.43794136 0.63274383 0.60079662]]


In [40]:
df = pd.DataFrame(data=data, columns=["A","B", "C"])
df

A         B         C
0  0.475093  0.204799  0.661625
1  0.516528  0.463975  0.944091
2  0.453809  0.150762  0.675615
3  0.825016  0.479821  0.682639
4  0.437941  0.632744  0.600797

In [41]:
df = pd.DataFrame(data={"A" : [1,2,3],
                        "B" : ["Div", "Appi", "Abhi"]})
df

A     B
0  1   Div
1  2  Appi
2  3  Abhi

In [43]:
#structured array
dtype = [("A", np.int),("B", (np.str, 20))]
data = np.array([(1,"Sam"), (2,"Alex"), (3,"John")], dtype=dtype)
print(data)

[(1, 'Sam') (2, 'Alex') (3, 'John')]


<ipython-input-43-9f89f6c304c5>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int),("B", (np.str, 20))]
<ipython-input-43-9f89f6c304c5>:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int),("

In [44]:
dtype = [("A", np.int),("B", (np.str, 20))]
data = np.array([(1,"Sam"), (2,"Alex"), (3,"John")], dtype=dtype)
pd.DataFrame(data)

<ipython-input-44-ce97eb5a0a80>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int),("B", (np.str, 20))]
<ipython-input-44-ce97eb5a0a80>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int),("

A     B
0  1   Sam
1  2  Alex
2  3  John

In [45]:
data = [{"A":1, "B":"Sam"}, {"A":2, "B":"Alex"}, {"A":3, "B":"John"}]
pd.DataFrame(data)

A     B
0  1   Sam
1  2  Alex
2  3  John

In [47]:
#Saving and Serialising
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.random(size=(100000,4)), columns=["A","B","C","D"])
df.head()

A         B         C         D
0  0.899579  0.212252  0.359984  0.031621
1  0.011052  0.999249  0.694792  0.454083
2  0.101047  0.359584  0.584410  0.469607
3  0.996121  0.993948  0.559890  0.627591
4  0.190258  0.659405  0.124771  0.424860

In [52]:
df.to_csv("/Users/divya/AIML/Cr-03-PythonAndPandasForDataAnalysisAndDataManipulation/Save.csv",
          index=False,
          float_format="%0.4f")

In [54]:
df.to_pickle("/Users/divya/AIML/Cr-03-PythonAndPandasForDataAnalysisAndDataManipulation/Save.pkl")

In [55]:
df.to_hdf("/Users/divya/AIML/Cr-03-PythonAndPandasForDataAnalysisAndDataManipulation/Save.hdf",
          key="data",
          format="table")

In [56]:
df = pd.read_csv('/Users/divya/AIML/Cr-03-PythonAndPandasForDataAnalysisAndDataManipulation/Materials/P87-Section-2-Dataset-Basics-Resources/P87-S2-Dataset-Basics-Resources/astronauts.csv')

In [57]:
df.head()

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired   3/3/1946     Warsaw, NY   Male   
3   Thomas D. Akers  1987.0   12.0  Retired  5/20/1951  St. Louis, MO   Male   
4       Buzz Aldrin  1963.0    3.0  Retired  1/20/1930  Montclair, NJ   Male   

                                          Alma Mater     Undergraduate Major  \
0  University of California-Santa Barbara; Univer...                 Geology   
1   Montana State University; University of Colorado     Engineering Physics   
2          US Military Academy; Princeton University             Engineering   
3                       University of Missouri-Rolla     Applied Mathematics   
4                           US Military Academy; MIT  Mechanical Engineering   

          Graduate Major Military Rank         Military Branch  Space Flights  \
0                Geology           NaN                     NaN              2   
1          Solar Physics           NaN                     NaN              1   
2  Aerospace Engineering       Colonel       US Army (Retired)              2   
3    Applied Mathematics       Colonel  US Air Force (Retired)              4   
4           Astronautics       Colonel  US Air Force (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   
3                814            4              29.0   
4                289            2               8.0   

                                            Missions Death Date Death Mission  
0             STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                              STS 51-F (Challenger)        NaN           NaN  
2               STS-28 (Columbia), STS-43 (Atlantis)        NaN           NaN  
3  STS-41 (Discovery), STS-49 (Endeavor), STS-61 ...        NaN           NaN  
4                               Gemini 12, Apollo 11        NaN           NaN

In [58]:
#inspecting DataFrame
import pandas as pd
df = pd.read_csv('/Users/divya/AIML/Cr-03-PythonAndPandasForDataAnalysisAndDataManipulation/Materials/P87-Section-2-Dataset-Basics-Resources/P87-S2-Dataset-Basics-Resources/astronauts.csv')
df.head()

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired   3/3/1946     Warsaw, NY   Male   
3   Thomas D. Akers  1987.0   12.0  Retired  5/20/1951  St. Louis, MO   Male   
4       Buzz Aldrin  1963.0    3.0  Retired  1/20/1930  Montclair, NJ   Male   

                                          Alma Mater     Undergraduate Major  \
0  University of California-Santa Barbara; Univer...                 Geology   
1   Montana State University; University of Colorado     Engineering Physics   
2          US Military Academy; Princeton University             Engineering   
3                       University of Missouri-Rolla     Applied Mathematics   
4                           US Military Academy; MIT  Mechanical Engineering   

          Graduate Major Military Rank         Military Branch  Space Flights  \
0                Geology           NaN                     NaN              2   
1          Solar Physics           NaN                     NaN              1   
2  Aerospace Engineering       Colonel       US Army (Retired)              2   
3    Applied Mathematics       Colonel  US Air Force (Retired)              4   
4           Astronautics       Colonel  US Air Force (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   
3                814            4              29.0   
4                289            2               8.0   

                                            Missions Death Date Death Mission  
0             STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                              STS 51-F (Challenger)        NaN           NaN  
2               STS-28 (Columbia), STS-43 (Atlantis)        NaN           NaN  
3  STS-41 (Discovery), STS-49 (Endeavor), STS-61 ...        NaN           NaN  
4                               Gemini 12, Apollo 11        NaN           NaN

In [59]:
df.tail()

Name    Year  Group   Status Birth Date  \
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \
352  STS-58 (Columbia). STS-86/89 (Atlantis/Endeavo...        NaN   
353                                                NaN        NaN   
354                                          Apollo 15        NaN   
355  Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS...        NaN   
356            STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
352           NaN  
353           NaN  
354           NaN  
355           NaN  
356           NaN

In [ ]:
df.sample(5)#read random items from df

Name    Year  Group    Status  Birth Date  \
33           Frank Borman  1962.0    2.0   Retired   3/14/1928   
323      Richard H. Truly  1969.0    7.0   Retired  11/12/1937   
22        Daniel T. Barry  1992.0   14.0   Retired  12/30/1953   
274         Sally K. Ride  1978.0    8.0  Deceased   5/26/1951   
292  Margaret Rhea Seddon  1978.0    8.0   Retired   11/8/1947   

          Birth Place  Gender  \
33           Gary, IN    Male   
323       Fayette, MS    Male   
22        Norwalk, CT    Male   
274   Los Angeles, CA  Female   
292  Murfreesboro, TN  Female   

                                            Alma Mater  \
33   US Military Academy; California Institute of T...   
323                    Georgia Institute of Technology   
22   Cornell University; Princeton University; Univ...   
274                                Stanford University   
292  University of California-Berkeley; University ...   

          Undergraduate Major  \
33                        NaN   
323  Aeronautical Engineering   
22     Electrical Engineering   
274          Physics; English   
292                Physiology   

                                        Graduate Major Military Rank  \
33                            Aeronautical Engineering       Colonel   
323                                                NaN  Vice Admiral   
22   Electrical Engineering; Computer Science; Medi...           NaN   
274                                            Physics           NaN   
292                                           Medicine           NaN   

            Military Branch  Space Flights  Space Flight (hr)  Space Walks  \
33   US Air Force (Retired)              2                477            0   
323       US Navy (Retired)              2                199            0   
22                      NaN              3                733            4   
274                     NaN              2                343            0   
292                     NaN              3                722            0   

     Space Walks (hr)                                           Missions  \
33                0.0                                 Gemini 7, Apollo 8   
323               0.0               STS-2 (Columbia), STS-8 (Challenger)   
22               26.0  STS-72 (Endeavor), STS-96 (Discovery), STS-105...   
274               0.0          STS-7 (Challenger), STS 41-G (Challenger)   
292               0.0  STS 51-D (Discovery), STS-40 (Columbia), STS-5...   

    Death Date Death Mission  
33         NaN           NaN  
323        NaN           NaN  
22         NaN           NaN  
274  7/23/2012           NaN  
292        NaN           NaN

In [62]:
df.sample(5, replace=True)

Name    Year  Group   Status  Birth Date  \
11   Dominic A. Antonelli  2000.0   18.0   Active   8/23/1967   
292  Margaret Rhea Seddon  1978.0    8.0  Retired   11/8/1947   
138    William G. Gregory  1990.0   13.0  Retired   5/14/1957   
238       Steven R. Nagel  1978.0    8.0  Retired  10/27/1946   
237        Story Musgrave  1967.0    6.0  Retired   8/19/1935   

          Birth Place  Gender  \
11        Detroit, MI    Male   
292  Murfreesboro, TN  Female   
138      Lockport, NY    Male   
238        Canton, IL    Male   
237        Boston, MA    Male   

                                            Alma Mater  \
11                       MIT; University of Washington   
292  University of California-Berkeley; University ...   
138  US Air Force Academy; Columbia University; Tro...   
238  University of Illinois; California State Unive...   
237  Syracuse University; Marietta College; Univers...   

                     Undergraduate Major  \
11            Aeronautics & Astronautics   
292                           Physiology   
138                  Engineering Science   
238                Aerospace Engineering   
237  Mathematics & Statistics; Chemistry   

                                        Graduate Major       Military Rank  \
11                          Aeronautics & Astronautics           Commander   
292                                           Medicine                 NaN   
138         Engineering Mechanics; Business Management  Lieutenant Colonel   
238                            Mechanical  Engineering             Colonel   
237  Business Administration; Physiology; Literatur...                 NaN   

            Military Branch  Space Flights  Space Flight (hr)  Space Walks  \
11                  US Navy              2                579            0   
292                     NaN              3                722            0   
138            US Air Force              1                399            0   
238  US Air Force (Retired)              4                721            0   
237                     NaN              6               1281            4   

     Space Walks (hr)                                           Missions  \
11                0.0            STS-119 (Discovery), STS-132 (Atlantis)   
292               0.0  STS 51-D (Discovery), STS-40 (Columbia), STS-5...   
138               0.0                                  STS-67 (Endeavor)   
238               0.0  STS 51-G (Discovery), STS 61-A (Challenger), S...   
237              26.0  STS-6 (Challenger), STS 51-F (Challenger), STS...   

    Death Date Death Mission  
11         NaN           NaN  
292        NaN           NaN  
138        NaN           NaN  
238        NaN           NaN  
237        NaN           NaN

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Name                 357 non-null    object 
 1   Year                 330 non-null    float64
 2   Group                330 non-null    float64
 3   Status               357 non-null    object 
 4   Birth Date           357 non-null    object 
 5   Birth Place          357 non-null    object 
 6   Gender               357 non-null    object 
 7   Alma Mater           356 non-null    object 
 8   Undergraduate Major  335 non-null    object 
 9   Graduate Major       298 non-null    object 
 10  Military Rank        207 non-null    object 
 11  Military Branch      211 non-null    object 
 12  Space Flights        357 non-null    int64  
 13  Space Flight (hr)    357 non-null    int64  
 14  Space Walks          357 non-null    int64  
 15  Space Walks (hr)     357 non-null    flo

In [65]:
df.describe()

Year       Group  Space Flights  Space Flight (hr)  Space Walks  \
count   330.000000  330.000000     357.000000         357.000000   357.000000   
mean   1985.106061   11.409091       2.364146        1249.266106     1.246499   
std      13.216147    5.149962       1.428700        1896.759857     2.056989   
min    1959.000000    1.000000       0.000000           0.000000     0.000000   
25%    1978.000000    8.000000       1.000000         289.000000     0.000000   
50%    1987.000000   12.000000       2.000000         590.000000     0.000000   
75%    1996.000000   16.000000       3.000000        1045.000000     2.000000   
max    2009.000000   20.000000       7.000000       12818.000000    10.000000   

       Space Walks (hr)  
count        357.000000  
mean           7.707283  
std           13.367973  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           12.000000  
max           67.000000

In [66]:
df.shape

(357, 19)

In [67]:
df.corr()

Year     Group  Space Flights  Space Flight (hr)  \
Year               1.000000  0.980934       0.036420           0.331386   
Group              0.980934  1.000000      -0.011386           0.325683   
Space Flights      0.036420 -0.011386       1.000000           0.325233   
Space Flight (hr)  0.331386  0.325683       0.325233           1.000000   
Space Walks        0.210073  0.217891       0.257073           0.472796   
Space Walks (hr)   0.253502  0.261384       0.258642           0.454408   

                   Space Walks  Space Walks (hr)  
Year                  0.210073          0.253502  
Group                 0.217891          0.261384  
Space Flights         0.257073          0.258642  
Space Flight (hr)     0.472796          0.454408  
Space Walks           1.000000          0.985755  
Space Walks (hr)      0.985755          1.000000

In [68]:
df['Year'].value_counts()

1996.0    35
1978.0    35
1998.0    25
1990.0    23
1966.0    19
1995.0    19
1992.0    19
1980.0    19
1984.0    18
2000.0    17
1987.0    15
1963.0    14
1985.0    13
2004.0    11
1967.0    11
2009.0     9
1962.0     8
1959.0     7
1969.0     7
1965.0     6
Name: Year, dtype: int64

In [69]:
df.max()

Name                 Yvonne D. Cagle
Year                          2009.0
Group                           20.0
Status                       Retired
Birth Date                  9/9/1952
Birth Place              Yonkers, NY
Gender                          Male
Space Flights                      7
Space Flight (hr)              12818
Space Walks                       10
Space Walks (hr)                67.0
dtype: object

In [70]:
df.min()

Name                 Alan B. Shepard Jr. 
Year                               1959.0
Group                                 1.0
Status                             Active
Birth Date                      1/14/1943
Birth Place                  Abington, PA
Gender                             Female
Space Flights                           0
Space Flight (hr)                       0
Space Walks                             0
Space Walks (hr)                      0.0
dtype: object

In [ ]:
df